export const GET_FOOD = 'GET_FOOD'
export const POST_FOOD = 'POST_FOOD'
export const POST_USER = 'POST_USER'
export const GET_USER = 'GET_USER'
export const POST_COMBINATION = 'POST_COMBINATION'
export const LOGOUT = 'LOGOUT'